variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)
  SDK_VERSION: 3.x

trigger:
  - master
  - refs/tags/v*

pr:
  branches:
    include:
      - master

jobs:
  - template: jobs/build_and_test.yml
    parameters:
      name: linux
      vmImage: 'ubuntu-18.04'
